version: '3.8'
services:
  web:
    build: .
    ports:
      - '3008:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - pops_imagens:/app/src/imagens
    restart: unless-stopped

volumes:
  pops_imagens:
